# Have the build run on every push
name: Build (linux)
on: [push]

# Define the actual build job
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Perform the build operation
      - name: Build SDL Library
        run: |
          mkdir -p build-linux
          cd build-linux/
          ../configure
          make
          cd ..

      # Zip/package the build artifacts
      - name: Package SDL Library
        run: |
          tar -zcvf libSDL2.linux-x86.tar.gz ./build-linux/build/.libs/libSDL*.so ./build-linux/include

      # Upload the build artifacts (x86)
      - name: Upload SDL packaged Library (x86)
        uses: actions/upload-artifact@v2
        with:
          name: linux-x86
          path: libSDL2.linux-x86.tar.gz
