# Have the build run on every push
name: Build (macos)
on: [push]

# Define the actual build job
jobs:
  build-macos:
    runs-on: macos-latest
    steps:

      # Perform the build operation
      - uses: actions/checkout@v2
      - run: |
          mkdir -p build-mac
          cd build-mac/
          CC=../build-scripts/clang-fat.sh ../configure
          make

      # Zip/package the build artifacts
      - run: cp -r ./build-mac/include ./build-mac/x64/build/.libs/
      - run: tar -zcvf libSDL2.darwin-x64.tar.gz ./build-mac/x64/build/.libs/libSDL*.dylib
      - run: cp -r ./build-mac/include ./build-mac/arm64/build/.libs/
      - run: tar -zcvf libSDL2.darwin-arm64.tar.gz ./build-mac/arm64/build/.libs/libSDL*.dylib

      # Upload the build artifacts (x64)
      - uses: actions/upload-artifact@v2
        with:
          name: macos-x64
          path: libSDL2.darwin-x64.tar.gz

      # Upload the build artifacts (arm64)
      - uses: actions/upload-artifact@v2
        with:
          name: macos-arm64
          path: libSDL2.darwin-arm64.tar.gz
