# Have the release run on every tag push
name: Release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# Define the actual build job
# NOTE: We must run all builds first
jobs:
  release:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:

      # Ensure the output directories exist
      - name: Setup Output Directories
        run: |
            mkdir -p ~/output/linux
            mkdir -p ~/output/macos

      # Release the artifacts on GitHub
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Releasing artifacts for tag: ${{ github.ref }}
            - TODO - Add website for documenting relevant changes
          draft: false
          prerelease: false

      # Upload linux (x86) based artifacts to the release
      - name: Download x86 Linux Artifacts
        uses: actions/download-artifact@v2
        with:
          name: linux-x86
          path: ~/outputs/linux/
      - name: Upload Linux (x86) Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./outputs/linux/libSDL2.linux-x86.tar.gz
          asset_name: libSDL2.linux-x86.tar.gz
          asset_content_type: application/gzip
