# Have the release run on every tag push
name: Release
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# Define the actual build job
# NOTE: We must run all builds first
jobs:
  release:
    runs-on: macos-latest
    needs: build-macos
    steps:

      # Ensure the output directories exist
      - run: mkdir -p ~/output/macos/x64
      - run: mkdir -p ~/output/macos/arm64

      # Release the artifacts on GitHub
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Releasing artifacts for tag: ${{ github.ref }}
            - TODO - Add website for documenting relevant changes
          draft: false
          prerelease: false

      # Upload mac-os (x64) based artifacts to the release
      - name: Download x64 MacOS Artifacts
        uses: actions/download-artifact@v2
        with:
          name: macos-x64
          path: ~/outputs/macos/
      - name: Upload MacOS (x64) Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./outputs/libSDL2.darwin-x64.tar.gz
          asset_name: libSDL2.darwin-x64.tar.gz
          asset_content_type: application/gzip

      # Upload mac-os (arm64) based artifacts to the release
      - name: Download arm64 MacOS Artifacts
        uses: actions/download-artifact@v2
        with:
          name: macos-arm64
          path: ~/outputs/macos/
      - name: Upload MacOS (arm64) Release Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./outputs/libSDL2.darwin-arm64.tar.gz
          asset_name: libSDL2.darwin-arm64.tar.gz
          asset_content_type: application/gzip
